
-- require "user.bufferline"
-- require "user.hop"
-- require "user.ipy"
-- require "user.tmux"
-- require "user.trouble"
--[[ require "user.vimspector" ]]
require "user.plugins"
require "user.options"
require "user.chatgpt"
require "user.alpha"
-- require "user.formatting"
-- require "user.aerial"
require "user.autocommands"
require "user.codeium"
require "user.autopairs"
require "user.autosave"
require "user.cmp"
require "user.codi"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.impatient"
require "user.indentline"
require "user.iron"
require "user.jupytext"
require "user.keymaps"
require "user.lsp"
require "user.lualine"
require "user.luasnip"
require "user.mason"
require "user.project"
require "user.nvim-r"
require "user.nvim-surround"
require "user.nvim-tree"
require "user.symbols-outline"
-- require "user.tabby"
require "user.telescope"
-- require "user.jupynium"
require "user.textobjects"
require "user.toggleterm"
require "user.treesitter"
require "user.whichkey"
require "user.wrapping-keymaps"
require "user.clangd_extensions"
require "user.cmake-tools"
require "user.asyncrun"
require "user.matchparen"
require "user.autosession"
require "user.leap"
